input {
  http {
    port => 8080
    codec => json
  }
}

filter {
  if [stream_type] == "strava" {
    mutate {
      rename => { 
        "lat" => "latitude"
        "lon" => "longitude"
        "ele" => "elevation"
        "time" => "timestamp"
        "hr" => "heart_rate"
        "cad" => "cadence"
        "dist" => "distance"
      }
    }
    mutate {
      convert => {
        "latitude" => "float"
        "longitude" => "float"
        "elevation" => "float"
        "heart_rate" => "integer"
        "cadence" => "integer"
        "distance" => "float"
      }
    }
  }

  else if [stream_type] == "weather" {
    mutate {
      rename => {
        "time" => "timestamp"
        "temp" => "temperature"
        "hum" => "humidity"
      }
    }
    mutate {
      convert => {
        "temperature" => "float"
        "humidity" => "float"
      }
    }
  }

  else if [stream_type] == "airquality" {
    mutate {
      rename => {
        "time" => "timestamp"
        "pm25" => "pm2_5"
      }
    }
    mutate {
      convert => {
        "aqi" => "integer"
        "pm2_5" => "float"
      }
    }
  }
}

output {
  if [stream_type] == "weather" {
    kafka {
      bootstrap_servers => "broker:9092"
      topic_id => "weatherdata"
      codec => json
    }
  } else if [stream_type] == "airquality" {
    kafka {
      bootstrap_servers => "broker:9092"
      topic_id => "airquality"
      codec => json
    }
  } else {
    kafka {
      bootstrap_servers => "broker:9092"
      topic_id => "running-live-data"
      codec => json
    }
  }

  stdout { codec => rubydebug }
}