apiVersion: 1

datasources:
  - name: Redis
    type: redis-datasource
    uid: redis-ds
    access: proxy
    url: redis:6379
    isDefault: true
    jsonData:
      client: text
      
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    uid: elasticsearch-ds
    jsonData:
      index: strava_metrics
      timeField: timestamp
      version: "8.11.4"